-- -------------------------------------------------------------------------------
-- -- Project: AscensionTooltip
-- -- Author: Aka-DoctorCode 
-- -- File: AscensionTooltip.lua
-- -- Version: 12.0.0
-- -------------------------------------------------------------------------------
-- -- Copyright (c) 2025–2026 Aka-DoctorCode. All Rights Reserved.
-- --
-- -- This software and its source code are the exclusive property of the author.
-- -- No part of this file may be copied, modified, redistributed, or used in 
-- -- derivative works without express written permission.
-- --------------------------------------------------------------------------------- ==========================================================
-- -- AscensionTooltip - Version 5.0.0
-- -- ==========================================================
-- local ADDON_NAME = "AscensionTooltip"
-- local AscensionTooltip = LibStub("AceAddon-3.0"):NewAddon(ADDON_NAME, "AceConsole-3.0", "AceEvent-3.0", "AceTimer-3.0")
